[target.x86_64-unknown-linux-gnu]
  linker = "clang"
  rustflags = ["-C", 
    "link-arg=-fuse-ld=/nix/store/46n1qljc0drdz4r2k9smxxb8kl79di25-mold-2.32.1/bin/mold", 
  ]

[build]
target = "x86_64-unknown-linux-musl"
